//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRow
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int MovieId { get; set; }
        public decimal Price { get; set; }
    
        public virtual Movie Movy { get; set; }
        public virtual Order Order { get; set; }
    }
}
